insert into VACATION(VACATION_ID,NAME,DESTINATION,NO_OF_DAYS) values(1,'INDIA-NORTH','MANLI',5);
insert into VACATION(VACATION_ID,NAME,DESTINATION,NO_OF_DAYS) values(2,'INDIA-SOUTH','COCHIN',4);
insert into VACATION(VACATION_ID,NAME,DESTINATION,NO_OF_DAYS) values(3,'INDIA-ANDAMAN','ISLAND',6);

insert into REVIEW(REVIEW_ID,RATING,COMMENT,VACATION_ID) values(1,'4.5*','EXCELLENT DESTINATION',1);
insert into REVIEW(REVIEW_ID,RATING,COMMENT,VACATION_ID) values(2,'3','NOT BAD',1);


insert into REVIEW(REVIEW_ID,RATING,COMMENT,VACATION_ID) values(3,'3*','GOOD FOR COUPLE',2);
insert into REVIEW(REVIEW_ID,RATING,COMMENT,VACATION_ID) values(4,'2*','ACCOMMODATION IS NOT GOOD',2);

insert into REVIEW(REVIEW_ID,RATING,COMMENT,VACATION_ID) values(5,'3*','GOOD FOR COUPLE',3);
